### ISSUE TITLE
Add the function to load the YAML configuration file

### ISSUE THREAD

**Issue by taicaile** [taicaile/Jenkinslib#1]
1. There shall be a function to load the yaml format configuration file. The configuration file is from other repo, and it shall be as an input parameter.
2. The pipeline shall be able to run the stages && commands according the configuration file. Like Build, Post Command, Binary Upload, Console Log upload, Chat && Email Notification.

**Comment by taicaile** [comment]
Add sample configuration file:

```yaml
- name: BuildStage
  type: bat
  BuildCommand: "build"
  BuildDirectory:
```
